(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const W = 1000, H = 620, SAVE = 'luna-star-routes-v1', SETTINGS = 'luna-settings-v1';
  const ROUTES = [
    {name:'はじまりの軌道',sector:'第一宙域 · はじまり',note:'星屑をひとつずつ集めて、灯台へ。',start:[105,310],goal:[900,310],stars:[[300,310],[520,310],[720,310]],fuel:4,bodies:[]},
    {name:'ひかりの井戸',sector:'第一宙域 · はじまり',note:'惑星のそばを通ると、軌道が曲がる。',start:[110,480],goal:[885,135],stars:[[300,395],[550,280],[760,190]],fuel:4,bodies:[[475,350,54,30000]]},
    {name:'双子星のあいだ',sector:'第一宙域 · はじまり',note:'二つの引力の間に、静かな道を見つけよう。',start:[110,310],goal:[890,310],stars:[[285,215],[510,402],[745,214]],fuel:5,bodies:[[425,270,43,23000],[585,350,43,23000]]},
    {name:'薄明の環',sector:'第二宙域 · 星の環',note:'環の外側をなぞると、遠回りも近道になる。',start:[100,500],goal:[900,120],stars:[[280,430],[500,315],[765,190]],fuel:5,bodies:[[500,310,76,39000],[720,395,33,10000]]},
    {name:'青い巨星',sector:'第二宙域 · 星の環',note:'強い引力を味方にして、遠くへ跳ぼう。',start:[105,315],goal:[895,315],stars:[[285,430],[510,140],[745,425]],fuel:4,bodies:[[500,310,69,65000]]},
    {name:'漂流する月',sector:'第二宙域 · 星の環',note:'小さな月も、そっと船を引き寄せる。',start:[110,520],goal:[885,110],stars:[[270,435],[520,310],[750,190]],fuel:5,bodies:[[340,390,42,17000],[650,220,50,26000]]},
    {name:'影の回廊',sector:'第三宙域 · 彼方',note:'星を結ぶように進んで、影の向こうへ。',start:[110,300],goal:[890,300],stars:[[265,180],[500,430],[740,180]],fuel:5,bodies:[[385,300,62,42000],[615,300,62,42000],[500,490,29,13000]]},
    {name:'三つの灯',sector:'第三宙域 · 彼方',note:'三つの重力が交わる場所を抜ける。',start:[100,510],goal:[900,110],stars:[[270,400],[500,310],[750,210]],fuel:6,bodies:[[330,365,40,25000],[505,310,49,37000],[680,250,40,25000]]},
    {name:'遠日点',sector:'第三宙域 · 彼方',note:'大きく弧を描く。遠い星ほど、よく見える。',start:[105,310],goal:[895,310],stars:[[260,445],[500,450],[745,445]],fuel:4,bodies:[[500,205,74,78000]]},
    {name:'静かな連星',sector:'第四宙域 · 余白',note:'引く力の向きを見て、短い噴射を重ねよう。',start:[100,500],goal:[900,120],stars:[[270,430],[510,300],[760,200]],fuel:6,bodies:[[390,365,47,34000],[620,235,47,34000]]},
    {name:'星屑の大河',sector:'第四宙域 · 余白',note:'星の川をたどり、最後の灯りを探して。',start:[105,300],goal:[900,300],stars:[[240,220],[390,390],[560,220],[720,390]],fuel:6,bodies:[[460,300,55,43000],[680,290,48,35000]]},
    {name:'名前のない星',sector:'第四宙域 · 余白',note:'夜空の向こうに、あなたの星を見つけよう。',start:[100,520],goal:[900,100],stars:[[245,435],[410,330],[590,230],[760,160]],fuel:7,bodies:[[340,360,43,28000],[530,275,48,37000],[700,200,39,25000]]}
  ];
  const app=$('app'), sky=$('sky'), skyCtx=sky.getContext('2d'), field=$('field'), ctx=field.getContext('2d');
  const views={title:$('title'),map:$('map'),play:$('play')};
  let view='title', routeIndex=0, state=null, pointer=null, last=0, time=0, stars=[], audio=null, sound=true, reduced=false, predict=true, toastTimer=0, dpr=1, scale=1, ox=0, oy=0;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function load(){try{const d=JSON.parse(localStorage.getItem(SAVE)||'{}');return {cleared:Array.isArray(d.cleared)?d.cleared.filter(n=>Number.isInteger(n)&&n>=0&&n<ROUTES.length):[], shards:Array.isArray(d.shards)?d.shards.filter(n=>Number.isInteger(n)&&n>=0&&n<ROUTES.length):[]}}catch(_){return {cleared:[],shards:[]}}}
  let record=load();
  try{const s=JSON.parse(localStorage.getItem(SETTINGS)||'{}');sound=s.sound!==false;reduced=s.reduced===true}catch(_){}
  app.classList.toggle('reduce-motion',reduced);
  function save(){try{localStorage.setItem(SAVE,JSON.stringify(record))}catch(_){toast('記録を保存できませんでした。遊びは続けられます。')}}
  function saveSettings(){try{localStorage.setItem(SETTINGS,JSON.stringify({sound,reduced}))}catch(_){}}
  function setView(name){view=name;app.dataset.view=name;Object.entries(views).forEach(([k,v])=>v.hidden=k!==name);if(name==='map')drawMap();if(name==='play'){resizeField();drawHud();requestAnimationFrame(()=>{resizeField();render()})}if(name==='title')updateRecord()}
  function updateRecord(){$('record').textContent=record.cleared.length?`${record.cleared.length} / ${ROUTES.length} の航路に、灯りを残した。`:'夜空には、まだ名前のない星がある。'}
  function unlocked(i){return i===0||record.cleared.includes(i-1)}
  function drawMap(){const list=$('routeList');list.replaceChildren();for(let i=0;i<ROUTES.length;i++){const r=ROUTES[i],b=document.createElement('button');b.type='button';b.className='route-card'+(unlocked(i)?'':' locked')+(record.cleared.includes(i)?'':' current');b.disabled=!unlocked(i);const n=r.stars.length,label=record.shards.includes(i)?`✦ ${n} / ${n}`:`✧ 0 / ${n}`;b.innerHTML=`<span class="route-num">ROUTE ${String(i+1).padStart(2,'0')} · ${r.sector.split(' · ')[0]}</span><span class="route-stars">${label}</span><strong>${r.name}</strong><small>${r.fuel} 回噴射${record.cleared.includes(i)?' · 記録あり':''}</small>`;b.addEventListener('click',()=>startRoute(i));list.append(b)}$('mapProgress').textContent=`航路の記録　${record.cleared.length} / ${ROUTES.length}　·　星屑　${record.shards.length} / ${ROUTES.length}`}
  function startRoute(i){clearTimeout(toastTimer);$('toast').classList.remove('show');routeIndex=i;const r=ROUTES[i];state={x:r.start[0],y:r.start[1],vx:0,vy:0,fuel:r.fuel,shards:Array(r.stars.length).fill(false),burns:[],running:false,elapsed:0,finished:false,trail:[],flash:0,initial:{x:r.start[0],y:r.start[1],vx:0,vy:0,fuel:r.fuel,shards:Array(r.stars.length).fill(false),burns:[]}};setView('play');if(i===0&&!record.cleared.includes(0))showHow(true)}
  function drawHud(){const r=ROUTES[routeIndex];$('sector').textContent=r.sector.toUpperCase();$('missionName').textContent=r.name;$('missionNo').textContent=`ROUTE ${String(routeIndex+1).padStart(2,'0')}`;$('status').textContent=state?.running?'星屑を集めて、灯台へ。':r.note;$('fieldHint').textContent=state?.running?'DRAG FROM SHIP · RELEASE TO BURN':'DRAG FROM SHIP · RELEASE TO BURN';$('shardCount').textContent=`${state?.shards.filter(Boolean).length||0} / ${r.stars.length}`;$('fuelCount').textContent=state?.fuel??r.fuel;$('predictLabel').textContent=`軌道予測 ${predict?'ON':'OFF'}`}
  function resize(){dpr=Math.min(2,devicePixelRatio||1);sky.width=Math.round(innerWidth*dpr);sky.height=Math.round(innerHeight*dpr);skyCtx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.round(Math.min(180,innerWidth*innerHeight/7200))},(_,i)=>({x:(i*127.1%1000)/1000*innerWidth,y:(i*311.7%1000)/1000*innerHeight,r:.4+(i*37%11)/12,a:.2+(i*19%8)/10,p:i*.07}));resizeField()}
  function resizeField(){if(!field||!field.isConnected)return;const rect=field.getBoundingClientRect();if(!rect.width||!rect.height)return;field.width=Math.round(rect.width*dpr);field.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min(rect.width/W,rect.height/H);ox=(rect.width-W*scale)/2;oy=(rect.height-H*scale)/2}
  function drawSky(dt){const w=innerWidth,h=innerHeight;skyCtx.clearRect(0,0,w,h);for(const s of stars){const tw=reduced?.55:0.65+Math.sin(time*.8+s.p)*.3;skyCtx.globalAlpha=s.a*tw;skyCtx.fillStyle='#d7d5ff';skyCtx.beginPath();skyCtx.arc(s.x,s.y,s.r,0,Math.PI*2);skyCtx.fill()}skyCtx.globalAlpha=1;time+=dt}
  function grav(x,y){const r=ROUTES[routeIndex],g={x:0,y:0};for(const [bx,by,rad,power] of r.bodies){const dx=bx-x,dy=by-y,d2=dx*dx+dy*dy+1000,d=Math.sqrt(d2),a=power/d2;g.x+=dx/d*a;g.y+=dy/d*a}return g}
  function integrate(s,dt){const g=grav(s.x,s.y);s.vx+=g.x*dt;s.vy+=g.y*dt;s.x+=s.vx*dt;s.y+=s.vy*dt;s.elapsed=(s.elapsed||0)+dt;if((s.elapsed*60|0)%3===0){s.trail.push([s.x,s.y]);if(s.trail.length>36)s.trail.shift()}}
  function step(dt){if(!state||!state.running||state.finished)return;integrate(state,dt);const r=ROUTES[routeIndex];for(const [i,p] of r.stars.entries()){if(state.shards[i])continue;if(Math.hypot(state.x-p[0],state.y-p[1])<23){state.shards[i]=true;state.flash=.45;beep('shard');drawHud();toast('星屑をひとつ、船に。')}}for(const [bx,by,rad] of r.bodies){if(Math.hypot(state.x-bx,state.y-by)<rad+7){state.running=false;state.flash=1;beep('bump');showCrash();return}}if(state.x<5||state.x>W-5||state.y<5||state.y>H-5||state.elapsed>50){state.running=false;showCrash();return}if(Math.hypot(state.x-r.goal[0],state.y-r.goal[1])<38){if(state.shards.every(Boolean)){state.running=false;state.finished=true;finishRoute()}else if(!state.warned){state.warned=true;toast('星屑がまだ残っています。灯台の近くで待てます。')}}}
  function predictPath(ship,vel){const p={x:ship.x,y:ship.y,vx:vel.x,vy:vel.y,elapsed:0,trail:[]},arr=[];for(let i=0;i<360;i++){integrate(p,1/30);arr.push([p.x,p.y]);if(p.x<0||p.x>W||p.y<0||p.y>H||ROUTES[routeIndex].bodies.some(([x,y,r])=>Math.hypot(p.x-x,p.y-y)<r+5))break;if(Math.hypot(p.x-ROUTES[routeIndex].goal[0],p.y-ROUTES[routeIndex].goal[1])<38)break}return arr}
  function render(){if(view!=='play'||!state)return;const rect=field.getBoundingClientRect(),w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);const r=ROUTES[routeIndex];drawGrid();for(const [bx,by,rad,power] of r.bodies)drawBody(bx,by,rad,power);drawGoal(r.goal[0],r.goal[1]);for(const [i,p] of r.stars.entries())if(!state.shards[i])drawShard(p[0],p[1],i);if(state.trail.length>1){ctx.beginPath();state.trail.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle='#d3c7ff54';ctx.lineWidth=1.6;ctx.setLineDash([3,6]);ctx.stroke();ctx.setLineDash([])}if(pointer&&predict&&state.fuel>0){const dx=(pointer.x-state.x),dy=(pointer.y-state.y),len=Math.hypot(dx,dy);if(len>7){const v=Math.min(390,len*1.55),path=predictPath(state,{x:dx/len*v,y:dy/len*v});ctx.beginPath();path.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle='#a9f0f5aa';ctx.lineWidth=2;ctx.setLineDash([6,7]);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(state.x,state.y);ctx.lineTo(state.x+dx/len*Math.min(95,len),state.y+dy/len*Math.min(95,len));ctx.strokeStyle='#e5dcffcc';ctx.lineWidth=2;ctx.stroke();arrow(state.x+dx/len*Math.min(95,len),state.y+dy/len*Math.min(95,len),Math.atan2(dy,dx))}}drawShip(state.x,state.y,state.vx,state.vy);if(state.flash>0){ctx.fillStyle=`rgba(207,194,255,${state.flash*.07})`;ctx.fillRect(0,0,W,H);state.flash=Math.max(0,state.flash-.025)}ctx.restore()}
  function drawGrid(){ctx.strokeStyle='#aca7df0c';ctx.lineWidth=1;for(let x=50;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=30;y<H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let i=0;i<70;i++){const x=(i*157.1)%W,y=(i*71.7)%H;ctx.globalAlpha=.2+(i%5)*.07;ctx.fillStyle='#d7d2ff';ctx.fillRect(x,y,1.4,1.4)}ctx.globalAlpha=1}
  function drawBody(x,y,r,p){const glow=ctx.createRadialGradient(x,y,r*.35,x,y,r*2.8);glow.addColorStop(0,'#d7a4ff22');glow.addColorStop(1,'#ae8cff00');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(x,y,r*2.8,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(x,y,r*1.8,r*.78,-.21,0,Math.PI*2);ctx.strokeStyle='#c4b3ff35';ctx.lineWidth=1.1;ctx.stroke();const g=ctx.createRadialGradient(x-r*.35,y-r*.4,1,x,y,r);g.addColorStop(0,'#e3d7ff');g.addColorStop(.25,'#9485c9');g.addColorStop(.68,'#4c4c79');g.addColorStop(1,'#171b32');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e1d9ff48';ctx.stroke();ctx.fillStyle='#e2d7ff35';ctx.beginPath();ctx.arc(x-r*.25,y-r*.2,r*.18,0,Math.PI*2);ctx.fill()}
  function drawGoal(x,y){const pulse=.5+Math.sin(time*2.3)*.5;ctx.save();ctx.translate(x,y);ctx.rotate(time*.05);for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,25+i*10,12+i*5,i*.4,0,Math.PI*2);ctx.strokeStyle=`rgba(150,227,241,${.22-pulse*.07})`;ctx.lineWidth=1;ctx.stroke()}const g=ctx.createRadialGradient(0,0,1,0,0,34);g.addColorStop(0,'#edffff');g.addColorStop(.14,'#a7f6ff');g.addColorStop(.5,'#65d5e755');g.addColorStop(1,'#5ccfe900');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dafcff';ctx.beginPath();ctx.arc(0,0,4+pulse*1.4,0,Math.PI*2);ctx.fill();ctx.restore()}
  function drawShard(x,y,i){const pulse=1+Math.sin(time*2.8+i*1.7)*.12;ctx.save();ctx.translate(x,y);ctx.rotate(time*.23+i);ctx.scale(pulse,pulse);const g=ctx.createRadialGradient(0,0,1,0,0,26);g.addColorStop(0,'#ffe9b7aa');g.addColorStop(1,'#ffe9b700');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,26,0,Math.PI*2);ctx.fill();ctx.rotate(Math.PI/4);ctx.fillStyle='#f4e7bc';ctx.shadowColor='#ffe7a7';ctx.shadowBlur=15;ctx.fillRect(-6,-6,12,12);ctx.shadowBlur=0;ctx.restore()}
  function drawShip(x,y,vx,vy){const a=Math.atan2(vy||-1,vx||.01);ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.shadowColor='#d4bcff';ctx.shadowBlur=14;ctx.fillStyle='#f8efff';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-6);ctx.lineTo(-4,0);ctx.lineTo(-8,6);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#b7ecff';ctx.beginPath();ctx.arc(-2,0,2.2,0,Math.PI*2);ctx.fill();if(state.running&&Math.hypot(vx,vy)>30){ctx.beginPath();ctx.moveTo(-7,-3);ctx.lineTo(-15-(Math.sin(time*46)+1)*2.5,0);ctx.lineTo(-7,3);ctx.fillStyle='#ffbd9c';ctx.fill()}ctx.restore();ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.strokeStyle='#cbbdff20';ctx.lineWidth=1;ctx.stroke()}
  function arrow(x,y,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-10,-4);ctx.lineTo(-8,0);ctx.lineTo(-10,4);ctx.closePath();ctx.fillStyle='#e5dcff';ctx.fill();ctx.restore()}
  function coords(e){const rect=field.getBoundingClientRect();return{x:(e.clientX-rect.left-ox)/scale,y:(e.clientY-rect.top-oy)/scale}}
  function pointerDown(e){if(!state||state.finished||state.fuel<=0)return;const p=coords(e);if(Math.hypot(p.x-state.x,p.y-state.y)>66){toast('船の近くから、行きたい向きへドラッグ。');return}pointer=p;field.setPointerCapture(e.pointerId);e.preventDefault();render()}
  function pointerMove(e){if(pointer){pointer=coords(e);render()}}
  function pointerUp(e){if(!pointer||!state)return;const p=coords(e),dx=p.x-state.x,dy=p.y-state.y,len=Math.hypot(dx,dy);pointer=null;if(len<16){render();toast('もう少し長くドラッグして噴射。');return}if(state.fuel<=0){toast('推進剤がありません。');render();return}state.burns.push({x:state.x,y:state.y,vx:state.vx,vy:state.vy,fuel:state.fuel,shards:[...state.shards],elapsed:state.elapsed,trail:[...state.trail]});const speed=clamp(len*1.55,90,390);state.vx+=dx/len*speed;state.vy+=dy/len*speed;state.fuel--;state.running=true;state.warned=false;beep('burn');drawHud();render();e.preventDefault()}
  function reset(){if(!state)return;startRoute(routeIndex)}
  function undo(){if(!state?.burns.length){toast('戻せる噴射がありません。');return}const s=state.burns.pop();Object.assign(state,{x:s.x,y:s.y,vx:s.vx,vy:s.vy,fuel:s.fuel,shards:s.shards,elapsed:s.elapsed,trail:s.trail,running:false,finished:false});drawHud();render();toast('ひとつ前の噴射へ戻りました。')}
  function finishRoute(){record.cleared=[...new Set([...record.cleared,routeIndex])];if(state.shards.every(Boolean))record.shards=[...new Set([...record.shards,routeIndex])];save();beep('win');const complete=record.cleared.length===ROUTES.length;modal(`<p class="eyebrow">${complete?'THE LAST LIGHT':'ROUTE COMPLETE'}</p><h2 id="dialogTitle">${complete?'星の名前を、あなたに。':'灯りが、届いた。'}</h2><p>${complete?'12の航路を渡り、夜空に新しい星座が生まれました。':'探査船は灯台に到着しました。星屑を集めた航路は、星図に残ります。'}</p><div class="dialog-stat"><span>星屑<b>${state.shards.filter(Boolean).length} / ${state.shards.length}</b></span><span>噴射<b>${ROUTES[routeIndex].fuel-state.fuel}</b></span></div><div class="dialog-actions"><button data-action="map">航路図へ</button><button class="accent" data-action="next">${complete?'もう一度夜空へ':'次の航路へ'} ↗</button></div>`)}
  function showCrash(){modal(`<p class="eyebrow">A QUIET RESET</p><h2 id="dialogTitle">星のあいだで、ひと休み。</h2><p>惑星に近づきすぎたようです。航路はそのまま。噴射を少し変えて、もう一度。</p><div class="dialog-actions"><button data-action="map">航路図へ</button><button class="accent" data-action="reset">やりなおす ↺</button></div>`)}
  function showHow(first=false){modal(`<p class="eyebrow">HOW TO FLY</p><h2 id="dialogTitle">重力を借りて、航路を描く。</h2><p><b>船の近くから、行きたい向きへドラッグ。</b><br>離すと推進剤を使って噴射します。点線はこれからの軌道予測。<br><br>惑星の近くでは、引力で軌道が曲がります。<br>金色の星屑を全部集めて、青い灯台へ。<br><br>壁や惑星にぶつかったら、航路をやりなおせます。<br>時間制限はありません。短い噴射を試してみてください。</p><div class="dialog-actions"><button class="accent" data-action="close">${first?'航路を見てみる':'とじる'} ↗</button></div>`)}
  function showPause(){modal(`<p class="eyebrow">PAUSE</p><h2 id="dialogTitle">宇宙は、待っている。</h2><p>航路の途中です。いつでも続きを始められます。</p><div class="dialog-actions"><button data-action="map">航路図へ</button><button class="accent" data-action="close">つづける ↗</button></div>`)}
  function showSettings(){modal(`<p class="eyebrow">SETTINGS</p><h2 id="dialogTitle">夜の設定</h2><div class="dialog-actions"><button data-action="sound">音 ${sound?'ON':'OFF'}</button><button data-action="motion">星の動き ${reduced?'少なめ':'通常'}</button><button class="accent" data-action="close">とじる</button></div>`)}
  function modal(html){$('dialog').innerHTML=html;$('modal').hidden=false;$('dialog').focus();if(state)state.running=false}
  function closeModal(){ $('modal').hidden=true;if(state&&!state.finished)state.running=state.vx!==0||state.vy!==0 }
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
  function beep(kind){if(!sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC();if(audio.state==='suspended')audio.resume();const now=audio.currentTime;const notes=kind==='shard'?[880,1174]:kind==='win'?[523,659,784,1046]:kind==='bump'?[180,110]:[392,587];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=kind==='bump'?'sine':'triangle';o.frequency.setValueAtTime(f,now+i*.07);g.gain.setValueAtTime(.0001,now+i*.07);g.gain.exponentialRampToValueAtTime(.035,now+i*.07+.015);g.gain.exponentialRampToValueAtTime(.0001,now+i*.07+.22);o.connect(g);g.connect(audio.destination);o.start(now+i*.07);o.stop(now+i*.07+.24)})}catch(_){}}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='start'){setView('map')}else if(a==='title'){setView('title')}else if(a==='map'){closeModal();setView('map')}else if(a==='pause')showPause();else if(a==='settings')showSettings();else if(a==='how'||a==='help')showHow();else if(a==='close')closeModal();else if(a==='reset'){closeModal();reset()}else if(a==='undo')undo();else if(a==='predict'){predict=!predict;drawHud();render()}else if(a==='sound'){sound=!sound;saveSettings();showSettings()}else if(a==='motion'){reduced=!reduced;app.classList.toggle('reduce-motion',reduced);saveSettings();showSettings()}else if(a==='next'){closeModal();if(routeIndex+1<ROUTES.length&&unlocked(routeIndex+1))startRoute(routeIndex+1);else setView('map')}});
  field.addEventListener('pointerdown',pointerDown);field.addEventListener('pointermove',pointerMove);field.addEventListener('pointerup',pointerUp);field.addEventListener('pointercancel',()=>{pointer=null;render()});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('modal').hidden)closeModal();else if(view==='play')showPause()}if((e.key==='u'||e.key==='Backspace')&&view==='play'){e.preventDefault();undo()}if(e.key.toLowerCase()==='r'&&view==='play')reset()});
  window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state?.running)state.running=false});
  function frame(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;drawSky(dt);if(view==='play'&&state){let left=dt;while(left>0){const d=Math.min(left,1/120);step(d);left-=d}render()}requestAnimationFrame(frame)}
  resize();updateRecord();requestAnimationFrame(frame);
})();
